apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: __AGENTGATEWAY_GATEWAY_NAME__
  namespace: __AGENTGATEWAY_NAMESPACE__
spec:
  gatewayClassName: agentgateway
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: All
